version: 2

project_name: 42crunch-exporter

builds:
  - id: "42crunch-exporter"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.build={{ .Version }}
    binary: "{{ .ProjectName }}"
    skip: false

dockers_v2:
  - images:
      - vzconnect/{{ .ProjectName }}:{{ .Version }}-amd64
    dockerfile: Dockerfile.goreleaser
    platforms:
      - linux/amd64
    flags:
      - "--pull"
    tags:
      - "{{ .Version }}-amd64"
      - "{{ .Version }}-arm64"
    labels:
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.licenses: MIT

changelog:
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: Fixes
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Building and Packaging
      regexp: "^.*build[(\\w)]*:+.*$"
      order: 2
    - title: Documentation
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 3
    - title: Others
      order: 999
  filters:
    exclude:
      - '^test:'
      - '^Merge '
