name: goreleaser

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.calculate-version.outputs.version }}
      tag_name: ${{ steps.calculate-version.outputs.tag_name }}

    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Fetch all tags
      run: git fetch --force --tags

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
          go-version: 1.19

    - name: Run GoReleaser
      id: goreleaser-release
      uses: goreleaser/goreleaser-action@v4
      with:
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Calculate version
      id: calculate-version
      run: |
        tag_name=${{ fromJson(steps.goreleaser-release.outputs.metadata).tag }}
        version=${{ fromJson(steps.goreleaser-release.outputs.metadata).version }}
        echo "::set-output name=tag_name::$tag_name"
        echo "::set-output name=version::$version"

    - name: Upload goreleaser built binaries to artifact 42crunch-exporter.${{ steps.calculate-version.outputs.version }}
      uses: actions/upload-artifact@v4
      with:
        name: 42crunch-exporter.${{ steps.calculate-version.outputs.version }}
        path: |
          dist/*.zip
          dist/*.tar.gz
