on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please-release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          version-file: VERSION
          release-type: simple
          token: ${{ secrets.INTEGRATIONS_BOT_TOKEN }}
          command: github-release
  release-please-pr:
    runs-on: ubuntu-latest
    needs:
      - release-please-release
    steps:
      - id: release-pr
        uses: google-github-actions/release-please-action@v4
        with:
          version-file: VERSION
          token: ${{ secrets.INTEGRATIONS_BOT_TOKEN }}
          release-type: simple
          command: release-pr
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"refactor","section":"Miscellaneous","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false},{"type":"ci","section":"Miscellaneous","hidden":false}]'
